[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

