[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = 'let g:lsp_async_completion = 1'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'momota/junos.vim'
on_ft = ['junos']

